<?php
/**
 * EIROCA PORTAL SYSTEM - Framework to build Mobile site - GPL3 - See licence in eps.php
 *
 * @author Enrico Croce & Simona Burzio (staff@eiroca.net)
 * @copyright Copyright (C) 2003-2019 eIrOcA - Enrico Croce & Simona Burzio
 * @version 0.5.3
 * @link http://www.eiroca.net
 */
?>
<a id="Features"></a>
<h2>Features</h2>
<p>Simple Portal Library optimized for mobile portals.</p>

<a id="Requirements"></a>
<h2>Requirements</h2>
<p>Apache 2.x and PHP 4.x</p>

<a id="Screenshots"></a>
<h2>Screenshots</h2>
<p>Coming soon.</p>

<a id="Demo"></a>
<h2>Demo</h2>
<p>Why demo? All the eIrOcA site is done with EPS.</p>

<a id="Download"></a>
<h2>Download</h2>
<p>
	Source code can be downloaded <a href="../apps/EPS/EPS.7z">here</a>.
</p>

<a id="ToDo"></a>
<h2>To Do</h2>
<ul>
	<li>Tons of things</li>
</ul>

<a id="ChangesLog"></a>
<h2>Changes log</h2>
<p>Version 0.4.0</p>
<ul>
	<li>First public release</li>
</ul>

<a id="Licence"></a>
<h2>Licence &amp; Copyright</h2>
<p>
	Copyright (C) 2006-2008 eIrOcA (eNrIcO Croce &amp; sImOnA Burzio)<br />
	&nbsp;<br /> This program is free software; you can redistribute it
	and/or modify it under the terms of the GNU General Public License as
	published by the Free Software Foundation; either version 2 of the
	License, or (at your option) any later version.<br /> &nbsp;<br /> This
	program is distributed in the hope that it will be useful, but WITHOUT
	ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
	FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
	for more details.<br /> &nbsp;<br /> You should have received a copy of
	the GNU General Public License along with this program; if not, write
	to:<br /> &nbsp;the Free Software Foundation, Inc.<br /> &nbsp;59
	Temple Place, Suite 330<br /> &nbsp;Boston, MA<br /> &nbsp;02111-1307
	USA<br />
</p>
<p>
	EPS includes:<br /> Image_Toolbox - Copyright (C) 2003 Martin Theimer<br />
	Smarty - Copyright (C) 2001-2005 New Digital Group, Inc.<br />
	MagpieRSS - Kellan Elliott-McCrea<br />
</p>
